name = "LightROM"
version = "0.1.0"
license = "BSD-3-Clause"
author = "Jean-Christophe"
maintainer = "loiseau.jc@gmail.com"
copyright = "Copyright 2024, Jean-Christophe"
description = "Lightweight fortran library for reduced-order modeling of LTI systems."

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
link = ["blas", "lapack"]

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = true
source-form = "free"

[dependencies]
stdlib = "*"
LightKrylov.git = "https://github.com/nekStab/LightKrylov"

[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"
test-drive.tag = "v0.4.0"

[[example]]

#---------------------------------------------------
#-----     SETUP FOR THE LAPLACIAN EXAMPLE     -----
#---------------------------------------------------

name = "Laplacian1D"
source-dir = "example/laplacian1D"

[example.dependencies]
rklib = { git="https://github.com/jacobwilliams/rklib.git" }

[[example]]

name = "Laplacian2D"
source-dir = "example/laplacian2D"

[example.dependencies]
rklib = { git="https://github.com/jacobwilliams/rklib.git" }
